from . import AbiIO as AbiIO, AceIO as AceIO, FastaIO as FastaIO, GckIO as GckIO, IgIO as IgIO, InsdcIO as InsdcIO, NibIO as NibIO, PdbIO as PdbIO, PhdIO as PhdIO, PirIO as PirIO, QualityIO as QualityIO, SeqXmlIO as SeqXmlIO, SffIO as SffIO, SnapGeneIO as SnapGeneIO, SwissIO as SwissIO, TabIO as TabIO, UniprotIO as UniprotIO, XdnaIO as XdnaIO
from Bio.Align import MultipleSeqAlignment as MultipleSeqAlignment
from Bio.Alphabet import Alphabet as Alphabet, AlphabetEncoder as AlphabetEncoder
from Bio.File import as_handle as as_handle
from Bio.SeqRecord import SeqRecord as SeqRecord
from Bio._py3k import basestring as basestring
from typing import Any, Optional

def write(sequences: Any, handle: Any, format: Any): ...
def parse(handle: Any, format: Any, alphabet: Optional[Any] = ...): ...
def read(handle: Any, format: Any, alphabet: Optional[Any] = ...): ...
def to_dict(sequences: Any, key_function: Optional[Any] = ...): ...
def index(filename: Any, format: Any, alphabet: Optional[Any] = ..., key_function: Optional[Any] = ...): ...
def index_db(index_filename: Any, filenames: Optional[Any] = ..., format: Optional[Any] = ..., alphabet: Optional[Any] = ..., key_function: Optional[Any] = ...): ...
def convert(in_file: Any, in_format: Any, out_file: Any, out_format: Any, alphabet: Optional[Any] = ...): ...
